; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=amdgcn -verify-machineinstrs < %s | FileCheck -enable-var-scope -check-prefix=GCN %s

define i32 @v_bfi_simple(i32 %x, i32 %y, i32 %z) {
; GCN-LABEL: v_bfi_simple:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    s_movk_i32 s4, 0x400
; GCN-NEXT:    v_bfi_b32 v0, s4, v0, v1
; GCN-NEXT:    s_setpc_b64 s[30:31]
entry:
  %bfi = call i32 @llvm.amdgcn.bfi(i32 1024, i32 %x, i32 %y)
  ret i32 %bfi
}

define i32 @v_bfi(i32 %x, i32 %y, i32 %z) {
; GCN-LABEL: v_bfi:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_bfi_b32 v0, 1, v0, v1
; GCN-NEXT:    v_bfi_b32 v0, 8, v0, v2
; GCN-NEXT:    s_setpc_b64 s[30:31]
entry:
  %bfi = call i32 @llvm.amdgcn.bfi(i32 1, i32 %x, i32 %y)
  %bfi.1 = call i32 @llvm.amdgcn.bfi(i32 8, i32 %bfi, i32 %z)
  ret i32 %bfi.1
}

define i32 @v_bfi_zero_mask(i32 %x, i32 %y, i32 %z) {
; GCN-LABEL: v_bfi_zero_mask:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mul_lo_u32 v0, v1, v2
; GCN-NEXT:    s_setpc_b64 s[30:31]
entry:
  %bfi = call i32 @llvm.amdgcn.bfi(i32 0, i32 %x, i32 %y)
  %ret = mul i32 %bfi, %z
  ret i32 %ret
}

define i32 @v_bfi_minus_one_mask(i32 %x, i32 %y, i32 %z) {
; GCN-LABEL: v_bfi_minus_one_mask:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mul_lo_u32 v0, v0, v2
; GCN-NEXT:    s_setpc_b64 s[30:31]
entry:
  %bfi = call i32 @llvm.amdgcn.bfi(i32 -1, i32 %x, i32 %y)
  %ret = mul i32 %bfi, %z
  ret i32 %ret
}

define i32 @v_bfi_non_const_mask(i32 %x, i32 %y, i32 %z, i32 %mask) {
; GCN-LABEL: v_bfi_non_const_mask:
; GCN:       ; %bb.0: ; %entry
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_bfi_b32 v0, v3, v0, v1
; GCN-NEXT:    v_mul_lo_u32 v0, v0, v2
; GCN-NEXT:    s_setpc_b64 s[30:31]
entry:
  %bfi = call i32 @llvm.amdgcn.bfi(i32 %mask, i32 %x, i32 %y)
  %ret = mul i32 %bfi, %z
  ret i32 %ret
}

declare i32 @llvm.amdgcn.bfi(i32, i32, i32)
